include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_redundant_argument_values: true
    unnecessary_late: true
    use_build_context_synchronously: false
    avoid_print: true
    always_declare_return_types: true
