include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    use_super_parameters: true
    unnecessary_this: false

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
